/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_Main */

#ifndef _Included_main_Main
#define _Included_main_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_Main
 * Method:    connect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_main_Main_connect(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
